"""Create podcast_episode table

Revision ID: 1a2b3c4d5e6f  # <-- This will be a unique hash
Revises:
Create Date: 2025-08-25 18:30:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('podcast_episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podcast_name', sa.String(length=255), nullable=False),
    sa.Column('episode_title', sa.String(length=512), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('compressed_transcription', sa.LargeBinary(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcast_episode_podcast_name'), 'podcast_episode', ['podcast_name'], unique=False)
    op.create_index(op.f('ix_podcast_episode_published_date'), 'podcast_episode', ['published_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcast_episode_published_date'), table_name='podcast_episode')
    op.drop_index(op.f('ix_podcast_episode_podcast_name'), table_name='podcast_episode')
    op.drop_table('podcast_episode')
    # ### end Alembic commands ###